<?php

require_once '/Users/enygma/work/writing/phpunit-article-3/app/Annotations.php';

/**
 * Test class for Annotations.
 * Generated by PHPUnit on 2011-02-05 at 12:47:20.
 */
class AnnotationsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Annotations
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Annotations;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (1,2) == 3.
     */
    public function testAddValues()
    {
        $this->assertEquals(
          3 ,
          $this->object->addValues(1,2)
        );
    }

    /**
     * @expectedException CustomException
     */
    public function testWillThrowException()
    {
	$this->object->willThrowException();
    }

    /**
     * @expectedExceptionCode 5
    public function testWillThrowExceptionCode()
    {
	$this->object->willThrowException();
    }
    */

    /**
     * @test
     * Generated from @assert (1,2) == 3.
     */
    public function isActuallyTest()
    {
        $this->assertEquals(
          3 ,
          $this->object->addValues(1,2)
        );
    }
}
?>
